<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NostrNet.Marmot.Mls.Reference\NostrNet.Marmot.Mls.Reference.csproj" />
    <ProjectReference Include="..\..\src\NostrNet.Marmot\NostrNet.Marmot.csproj" />
    <ProjectReference Include="..\..\src\NostrNet.Core\NostrNet.Core.csproj" />
    <ProjectReference Include="..\..\src\NostrNet.Crypto\NostrNet.Crypto.csproj" />
  </ItemGroup>

</Project>
