<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NostrNet</RootNamespace>
    <AssemblyName>NostrNet.Relay</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NostrNet.Core\NostrNet.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NostrNet.Relay.Tests" />
  </ItemGroup>

</Project>
